kind = "web"
previewPath = "/"
title = "Insta App"
version = "1.0.0"
id = "artifacts/insta-app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18612

[services.development]
run = "pnpm --filter @workspace/insta-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/insta-app", "run", "build" ]
publicDir = "artifacts/insta-app/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18612"
BASE_PATH = "/"
